definitions:
  common.init: &common_init
    initial_provider: x"03ECD350EEBC617CBBFBEF0A1B7AE553A748021FD65C7C50C5ABB4CA16D4EA5B05"
    genesis_node:
      - x"0350fe40766bc0ce8d08b3f5b810e49a8352fdd458606bd5fafe5acdcdc8ff3f57"
      - {hostName}
      - 9870
      - {apiUrl}
  config: &common_config
    blockstrategy:
      maxblocktime: 2000
    fast_revolt_status_timeout: 1000
    signers:
      - x"0350fe40766bc0ce8d08b3f5b810e49a8352fdd458606bd5fafe5acdcdc8ff3f57"

blockchains:
  manager:
    module: directory1
    config: *common_config
    moduleArgs:
      common.init: *common_init
  devnet:
    module: delta
    config: *common_config
    moduleArgs:
      common.init: *common_init
      auth_service:
        pubkey: x"02B6F2967CF9AFC4D289EF475A2C2DDEC9EAB79AC60C1C99683E3134074619E635"
      housekeeping:
        # 48h
        max_empty_container_time: 172800000
