image: registry.gitlab.com/chromaway/core-tools/chromia-cli/chr:0.20.3

.git_template: &git_setup |
  git remote set-url --push origin "https://oauth2:${BUILD_USER_GITLAB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
  git config user.name "build-user core-dev"
  git config user.email build_user@chromaway.com

.release:
  stage: release
  when: manual
  image: maven:3.8.4-jdk-11
  before_script:
    - set -eu
    - *git_setup
    - git checkout $CI_COMMIT_REF_NAME
    - CURRENT_VERSION=$(git describe --tags --abbrev=0)
    - IFS=. read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"

stages:
  - test
  - build
  - deploy
  - prepare_release
  - release

deploy:
  image: maven:3.8.4-jdk-11
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/
  script:
    - mvn
      $MAVEN_CLI_OPTS
      -Drevision=$CI_COMMIT_TAG
      deploy

test:
  services:
    - postgres
  stage: test
  script:
    - CASC_YAML_MAX_ALIASES=1000 chr install
    - chr test --test-report
  artifacts:
    when: always
    paths:
      - logs/*.log
    reports:
      junit:
        - "build/reports/*-tests.xml"
    expire_in: 1 week

compatibility:
  stage: test
  allow_failure: true
  script:
    - CASC_YAML_MAX_ALIASES=1000 chr install
    - ci/compatibility/verify_in_container.sh

build:
  services:
    - postgres
  stage: build
  script:
    - CASC_YAML_MAX_ALIASES=1000 chr install
    - find . -maxdepth 1 -name 'chromia*.yml' -print0  | xargs -0n 1 chr build --settings
  artifacts:
    when: on_success
    paths:
      - build/*.xml

release-minor:
  extends: .release
  script:
    - git tag $MAJOR.$((MINOR + 1)).0
    - git push --tags
  only:
    - dev

release-patch:
  extends: .release
  script:
    - git tag $MAJOR.$MINOR.$((PATCH + 1))
    - git push --tags
  only:
    - dev
    - /^support\/.*$/

pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/
  script:
    - chr install
    - chr generate docs-site --target public
  artifacts:
    paths:
      - public

prepare_release:
  stage: prepare_release
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
  script:
    - 'curl -H "PRIVATE-TOKEN: $TMP_CI_API_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/repository/changelog?version=$CI_COMMIT_TAG" | jq -r .notes > release_notes.md'
  artifacts:
    paths:
      - release_notes.md

gitlab-release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: prepare_release
      artifacts: true
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
  script:
    - echo "Release $CI_COMMIT_TAG"
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: release_notes.md
    tag_name: '$CI_COMMIT_TAG'

variables:
  GIT_DEPTH: 0
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -s ci/gitlab-settings.xml -U --file ci/pom.xml"
  POSTGRES_INITDB_ARGS: --lc-collate=C.UTF-8 --lc-ctype=C.UTF-8 --encoding=UTF-8
  POSTGRES_DB: postchain
  POSTGRES_USER: postchain
  POSTGRES_PASSWORD: postchain
  CHR_DB_URL: jdbc:postgresql://postgres/postchain
