image: registry.gitlab.com/chromaway/core-tools/chromia-cli/chr:0.17.0

.git_template: &git_setup |
  git remote set-url --push origin "https://oauth2:${BUILD_USER_GITLAB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git"
  git config user.name "build-user core-dev"
  git config user.email build_user@chromaway.com

.release:
  stage: release
  when: manual
  image: maven:3.8.4-jdk-11
  before_script:
    - set -eu
    - *git_setup
    - git checkout $CI_COMMIT_REF_NAME
    - CURRENT_VERSION=$(git describe --tags --abbrev=0)
    - IFS=. read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"

stages:
  - test
  - build
  - deploy
  - release

deploy:
  image: maven:3.8.4-jdk-11
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/
  script:
    - mvn
      $MAVEN_CLI_OPTS
      -Drevision=$CI_COMMIT_TAG
      deploy

test:
  services:
    - postgres
  stage: test
  script:
    - chr install
    - chr test --test-report
  artifacts:
    when: always
    paths:
      - logs/*.log
    reports:
      junit:
        - "build/reports/*-tests.xml"
    expire_in: 1 week

build:
  services:
    - postgres
  stage: build
  script:
    - chr install
    - chr build
  artifacts:
    when: on_success
    paths: 
      - build/*.xml

release-minor:
  extends: .release
  script:
    - git tag $MAJOR.$((MINOR + 1)).0
    - git push --tags
  only:
    - dev

release-patch:
  extends: .release
  script:
    - git tag $MAJOR.$MINOR.$((PATCH + 1))
    - git push --tags
  only:
    - dev
    - /^support\/.*$/

pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/
  script:
    - chr install
    - chr generate docs-site --target public
  artifacts:
    paths:
      - public

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -s ci/gitlab-settings.xml -U --file ci/pom.xml"
  POSTGRES_INITDB_ARGS: --lc-collate=C.UTF-8 --lc-ctype=C.UTF-8 --encoding=UTF-8
  POSTGRES_DB: postchain
  POSTGRES_USER: postchain
  POSTGRES_PASSWORD: postchain
  CHR_DB_URL: jdbc:postgresql://postgres/postchain
