definitions:
  common.init: &common_init
    initial_provider: ${INITIAL_PROVIDER:-03ECD350EEBC617CBBFBEF0A1B7AE553A748021FD65C7C50C5ABB4CA16D4EA5B05}
    genesis_node:
      - ${GENESIS_NODE:-0350fe40766bc0ce8d08b3f5b810e49a8352fdd458606bd5fafe5acdcdc8ff3f57}
      - ${GENESIS_HOST_NAME:-localhost}
      - 9870
      - ${GENESIS_API_URL:-http://localhost:7740}
  config: &common_config
    config_consensus_strategy: HEADER_HASH
    blockstrategy:
      maxblocktime: 2000
    revolt:
      fast_revolt_status_timeout: 2000
    signers:
      - x"0350fe40766bc0ce8d08b3f5b810e49a8352fdd458606bd5fafe5acdcdc8ff3f57"
    sync_ext:
      - "net.postchain.d1.icmf.IcmfReceiverSynchronizationInfrastructureExtension"
    gtx:
      modules:
        - "net.postchain.d1.icmf.IcmfReceiverGTXModule"
    icmf:
      receiver:
        anchoring:
          topics:
            - G_configuration_updated
            - G_configuration_failed

blockchains:
  manager:
    module: management_chain_directory1
    config: *common_config
    moduleArgs:
      common.init: *common_init
      common:
        enable_pcu: true
        allow_blockchain_dependencies: false
  devnet:
    module: management_chain_testnet
    config: *common_config
    moduleArgs:
      common.init: *common_init
      common:
        enable_pcu: true
        allow_blockchain_dependencies: false
      auth_service:
        pubkey: x"02B6F2967CF9AFC4D289EF475A2C2DDEC9EAB79AC60C1C99683E3134074619E635"
        include_system_cluster: true
      housekeeping:
        # 48h
        max_empty_container_time: 172800000
  system_anchoring:
    module: anchoring_chain_system
    config:
      config_consensus_strategy: HEADER_HASH
      blockstrategy:
        maxblocktime: 2000
      revolt:
        fast_revolt_status_timeout: 2000
      gtx:
        modules:
          - "net.postchain.d1.anchoring.system.SystemAnchoringGTXModule"
          - "net.postchain.d1.icmf.IcmfSenderGTXModule"
    moduleArgs:
      anchoring_chain_common:
        enable_pcu: true
  cluster_anchoring:
    module: anchoring_chain_cluster
    config:
      config_consensus_strategy: HEADER_HASH
      blockstrategy:
        maxblocktime: 2000
      revolt:
        fast_revolt_status_timeout: 2000
      gtx:
        modules:
          - "net.postchain.d1.anchoring.cluster.ClusterAnchoringGTXModule"
          - "net.postchain.d1.icmf.IcmfSenderGTXModule"
    moduleArgs:
      anchoring_chain_common:
        enable_pcu: true

database: # Used for running tests
  logSqlErrors: true
  schema: chain0test
  driver: org.postgresql.Driver

test:
  modules:
    - anchoring_chain_common.test
    - anchoring_chain_system.test
    - common.test
    - direct_cluster.test
    - direct_container.test
    - nm_api.test
    - proposal.test
    - proposal.voting.test
    - proposal_blockchain.test
    - proposal_cluster.test
    - proposal_cluster_anchoring.test
    - proposal_container.test
    - proposal_provider.test
    - proposal_voter_set.test
    - roles.test
    - roles.test
  moduleArgs:
    common:
      enable_pcu: true
      allow_blockchain_dependencies: true
    anchoring_chain_common:
      enable_pcu: true
