---
  - anonymous: 0
    inputs:
      - indexed: 1
        internalType: address
        name: sender
        type: address
      - indexed: 1
        internalType: contract IERC20
        name: token
        type: address
      - indexed: 0
        internalType: uint256
        name: networkId
        type: uint256
      - indexed: 0
        internalType: uint256
        name: amount
        type: uint256
      - indexed: 0
        internalType: string
        name: name
        type: string
      - indexed: 0
        internalType: string
        name: symbol
        type: string
      - indexed: 0
        internalType: uint8
        name: decimals
        type: uint8
    name: DepositedERC20
    type: event
