---
  - anonymous: 0
    name: StakeUpdate
    type: event
    inputs:
      - indexed: 1
        internalType: address
        name: from
        type: address
      - indexed: 0
        internalType: 
        name: balance
        type: uint64
  - anonymous: 0
    name: WithdrawRequest
    type: event
    inputs:
      - indexed: 1
        internalType: address
        name: from
        type: address
      - indexed: 0
        internalType: 
        name: until
        type: uint64